name: delivast_trial
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  get_it: ^5.0.3
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
